# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9e7902048eeb1f8b1d3a1e277edc6cc6c3201a0823326d5ae70c0e78881d7d5826a42136ed3147738af40d92340739329ab5292d3a39ac8ad27645a8e5cd718

test:
  secret_key_base: b156b12f3831fa3b75bd0fff335ffb428038409f6789add981d5a4d53ff7d41974183f3c91d9a173767d079f0d202425e352b0d2e4525baa18c177bb30414194

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
